.PHONY: clean build 21 22 23 24
	
clean:
	rm -rf build/
	
build:
	mkdir -p build/
	go build -o build/21 -v 21/main.go
	go build -o build/22 -v 22/main.go
	go build -o build/23 -v 23/main.go
	go build -o build/24 -v 24/main.go
	
21:
	./build/21
	
22:
	./build/22
	
23:
	./build/23
	
24:
	./build/24
