.PHONY: clean build 21 22 23 24 25 26 27
	
clean:
	rm -rf build/
	
build:
	mkdir -p build/
	go build -o build/21 -v 21/main.go
	go build -o build/22 -v 22/main.go
	go build -o build/23 -v 23/main.go
	go build -o build/24 -v 24/main.go
	go build -o build/25 -v 25/main.go
	go build -o build/26 -v 26/main.go
	go build -o build/27 -v 27/main.go
	
21:
	./build/21
	
22:
	./build/22
	
23:
	./build/23
	
24:
	./build/24
	
25:
	./build/25
	
26:
	./build/26
	
27:
	./build/27
