.PHONY: clean build 21 22 23 24 25 26 27 28 29 30
	
clean:
	rm -rf build/
	
build:
	mkdir -p build/
	go build -o build/21 -v 21/main.go
	go build -o build/22 -v 22/main.go
	go build -o build/23 -v 23/main.go
	go build -o build/24 -v 24/main.go
	go build -o build/25 -v 25/main.go
	go build -o build/26 -v 26/main.go
	go build -o build/27 -v 27/main.go
	go build -o build/28 -v 28/main.go
	go build -o build/29 -v 29/main.go
	go build -o build/30 -v 30/main.go
	
21:
	./build/21
	
22:
	./build/22
	
23:
	./build/23
	
24:
	./build/24
	
25:
	./build/25
	
26:
	./build/26
	
27:
	./build/27
	
28:
	./build/28
	
29:
	./build/29
	
30:
	./build/30
